"""Initial

Revision ID: 30fe396fc50b
Revises: 
Create Date: 2023-04-09 17:47:50.725065

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '30fe396fc50b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('city', sa.String(length=127), nullable=False),
                    sa.Column('name', sa.String(length=127), nullable=False),
                    sa.Column('url', sa.String(length=255), nullable=True),
                    sa.Column('metro', sa.String(length=127), nullable=True),
                    sa.Column('time_to_metro', sa.Integer(), nullable=True),
                    sa.Column('latitude', sa.Float(), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=True),
                    sa.Column('address', sa.String(length=255), nullable=True),
                    sa.Column('data_created', sa.Date(), nullable=False),
                    sa.Column('data_closed', sa.Date(), nullable=True),
                    sa.PrimaryKeyConstraint('project_id')
                    )
    op.create_table('flat',
                    sa.Column('flat_id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('address', sa.String(length=255), nullable=True),
                    sa.Column('floor', sa.Integer(), nullable=True),
                    sa.Column('rooms', sa.Integer(), nullable=True),
                    sa.Column('area', sa.Integer(), nullable=True),
                    sa.Column('finishing', sa.Boolean(), nullable=True),
                    sa.Column('bulk', sa.String(length=127), nullable=True),
                    sa.Column('settlement_date', sa.Date(), nullable=True),
                    sa.Column('url_suffix', sa.String(length=127), nullable=False),
                    sa.Column('data_created', sa.Date(), nullable=False),
                    sa.Column('data_closed', sa.Date(), nullable=True),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
                    sa.PrimaryKeyConstraint('flat_id')
                    )
    op.create_table('price',
                    sa.Column('price_id', sa.Integer(), nullable=False),
                    sa.Column('flat_id', sa.Integer(), nullable=False),
                    sa.Column('benefit_name', sa.String(length=127), nullable=True),
                    sa.Column('benefit_description', sa.String(length=255), nullable=True),
                    sa.Column('price', sa.Integer(), nullable=False),
                    sa.Column('meter_price', sa.Integer(), nullable=True),
                    sa.Column('booking_status', sa.String(length=15), nullable=True),
                    sa.Column('data_created', sa.Date(), nullable=False),
                    sa.ForeignKeyConstraint(['flat_id'], ['flat.flat_id'], ),
                    sa.PrimaryKeyConstraint('price_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    op.drop_table('flat')
    op.drop_table('project')
    # ### end Alembic commands ###
